.TH gearman_conf_parse_args 3 2009-07-02 "Gearman" "Gearman"
.SH NAME
gearman_conf_parse_args \- conf Gearman Conf Interface
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "GEARMAN_APIgearman_return_t gearman_conf_parse_args(gearman_conf_st " *conf ", int " argc ", char *argv[]);"
.SH DESCRIPTION
Parse command line arguments.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
