.TH gearman_client_do_high 3 2009-07-19 "Gearman" "Gearman"
.SH NAME
gearman_client_do_high \- Single Task Interface
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "void *gearman_client_do_high(gearman_client_st " *client ", const char " *function_name ", const char " *unique ", const void " *workload ", size_t " workload_size ", size_t " *result_size ", gearman_return_t *ret_ptr);"
.SH DESCRIPTION
Run a high priority task and return an allocated result. See
gearman_client_do() for parameter and return information.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
