.TH gearman_worker_free 3 2009-07-02 "Gearman" "Gearman"
.SH NAME
gearman_worker_free \- Worker Interface
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "GEARMAN_APIvoid gearman_worker_free(gearman_worker_st *worker);"
.SH DESCRIPTION
Free resources used by a worker structure.
.SH PARAMETERS
.TP
.BR worker
Worker structure previously initialized with
gearman_worker_create or gearman_worker_clone.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
