.TH gearman_client_do_status 3 2009-06-01 "Gearman" "Gearman"
.SH NAME
gearman_client_do_status \- Single Task Interface
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "void gearman_client_do_status(gearman_client_st " *client ", uint32_t " *numerator ", uint32_t *denominator);"
.SH DESCRIPTION
Get the status for the running task. This should be used between
repeated gearman_client_do() and gearman_client_do_high() calls to get
information.
.SH PARAMETERS
.TP
.BR client
Client structure previously initialized with
gearman_client_create or gearman_client_clone.
.TP
.BR numerator
Optional parameter to store the percent complete
numerator in.
.TP
.BR denominator
Optional parameter to store the percent complete
denominator in.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
