.TH gearman_server_worker_add 3 2009-06-01 "Gearman" "Gearman"
.SH NAME
gearman_server_worker_add \- Server Worker Handling
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "gearman_server_worker_st *gearman_server_worker_add(gearman_server_con_st " *server_con ", const char " *function_name ", size_t " function_name_size ", uint32_t timeout);"
.SH DESCRIPTION
Add a new worker to a server instance.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
