.TH gearmand_thread_free 3 2009-06-01 "Gearman" "Gearman"
.SH NAME
gearmand_thread_free \- Gearmand Threads
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "void gearmand_thread_free(gearmand_thread_st *thread);"
.SH DESCRIPTION
Free resources used by a thread.
.SH PARAMETERS
.TP
.BR thread
Thread previously initialized with gearmand_thread_create.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
