.TH gearman_client_clear_fn 3 2009-06-01 "Gearman" "Gearman"
.SH NAME
gearman_client_clear_fn \- Concurrent Task Interface
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "void gearman_client_clear_fn(gearman_client_st *client);"
.SH DESCRIPTION
Clear all task callback functions.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
