.TH gearman_set_queue_flush 3 2009-06-01 "Gearman" "Gearman"
.SH NAME
gearman_set_queue_flush \- Gearman Core Interface
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "void gearman_set_queue_flush(gearman_st " *gearman ", gearman_queue_flush_fn *flush_fn);"
.SH DESCRIPTION
Set function to call when the persistent queue should be flushed to disk.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
