.TH gearman_server_thread_set_event_watch 3 2009-06-01 "Gearman" "Gearman"
.SH NAME
gearman_server_thread_set_event_watch \- Server Thread Handling
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "void gearman_server_thread_set_event_watch(gearman_server_thread_st " *thread ", gearman_event_watch_fn " *event_watch ", void *event_watch_arg);"
.SH DESCRIPTION
Set custom I/O event watch callback.
.SH PARAMETERS
.TP
.BR thread
Thread structure previously initialized with
gearman_server_thread_create.
.TP
.BR event_watch
Function to be called when events need to be watched.
.TP
.BR event_watch_arg
Argument to pass along to event_watch.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
