.TH gearmand_con_free 3 2009-06-01 "Gearman" "Gearman"
.SH NAME
gearmand_con_free \- Gearmand Connections
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "void gearmand_con_free(gearmand_con_st *dcon);"
.SH DESCRIPTION
Free resources used by a connection.
.SH PARAMETERS
.TP
.BR dcon
Connection previously initialized with gearmand_con_create.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
