.TH gearman_client_add_servers 3 2009-06-01 "Gearman" "Gearman"
.SH NAME
gearman_client_add_servers \- Client Interface
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "gearman_return_t gearman_client_add_servers(gearman_client_st " *client ", const char *servers);"
.SH DESCRIPTION
Add a list of job servers to a client. The format for the server list is:
SERVER[:PORT][,SERVER[:PORT]]...
Some examples are:
10.0.0.1,10.0.0.2,10.0.0.3
localhost:1234,jobserver2.domain.com:7003,10.0.0.3
.SH PARAMETERS
.TP
.BR client
Client structure previously initialized with
gearman_client_create or gearman_client_clone.
.TP
.BR servers
Server list described above.
.SH "RETURN VALUE"
Standard gearman return value.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
