.TH gearman_task_is_running 3 2009-06-01 "Gearman" "Gearman"
.SH NAME
gearman_task_is_running \- Task Management
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "bool gearman_task_is_running(gearman_task_st *task);"
.SH DESCRIPTION
Get status on whether a task is running or not.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
