.TH gearman_con_set_recv_fn 3 2009-07-02 "Gearman" "Gearman"
.SH NAME
gearman_con_set_recv_fn \- Connection Handling
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "GEARMAN_APIvoid gearman_con_set_recv_fn(gearman_con_st " *con ", gearman_con_recv_fn recv_fn);"
.SH DESCRIPTION
Set custom recv function
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
