.TH gearman_conf_set_options 3 2009-07-02 "Gearman" "Gearman"
.SH NAME
gearman_conf_set_options \- conf Gearman Conf Interface
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "GEARMAN_APIvoid gearman_conf_set_options(gearman_conf_st " *conf ", gearman_conf_options_t " options ", uint32_t data);"
.SH DESCRIPTION
Set options for a gearman conf structure.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
