.TH gearman_client_set_options 3 2009-07-02 "Gearman" "Gearman"
.SH NAME
gearman_client_set_options \- Client Interface
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "GEARMAN_APIvoid gearman_client_set_options(gearman_client_st " *client ", gearman_client_options_t " options ", uint32_t data);"
.SH DESCRIPTION
Set options for a client structure.
.SH PARAMETERS
.TP
.BR client
Client structure previously initialized with
gearman_client_create or gearman_client_clone.
.TP
.BR options
Available options for gearman_client structs.
.TP
.BR data
For options that require parameters, the value of that parameter.
For all other option flags, this should be 0 to clear the option or 1
to set.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
