.TH gearmand_thread_wakeup 3 2009-07-19 "Gearman" "Gearman"
.SH NAME
gearmand_thread_wakeup \- Gearmand Threads
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "void gearmand_thread_wakeup(gearmand_thread_st " *thread ", gearmand_wakeup_t wakeup);"
.SH DESCRIPTION
Interrupt a running gearmand thread.
.SH PARAMETERS
.TP
.BR thread
Thread structure previously initialized with
gearmand_thread_create.
.TP
.BR wakeup
Wakeup event to send to running thread.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
