.TH gearman_worker_grab_job 3 2009-06-01 "Gearman" "Gearman"
.SH NAME
gearman_worker_grab_job \- Worker Interface
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "gearman_job_st *gearman_worker_grab_job(gearman_worker_st " *worker ", gearman_job_st " *job ", gearman_return_t *ret_ptr);"
.SH DESCRIPTION
Get a job from one of the job servers.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
