.TH gearman_server_con_io_next 3 2009-06-01 "Gearman" "Gearman"
.SH NAME
gearman_server_con_io_next \- Server Connection Handling
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "gearman_server_con_st *gearman_server_con_io_next(gearman_server_thread_st *thread);"
.SH DESCRIPTION
Get next connection from the io thread list.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
