.TH gearman_packet_unpack 3 2009-07-02 "Gearman" "Gearman"
.SH NAME
gearman_packet_unpack \- Packet Handling
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "GEARMAN_APIsize_t gearman_packet_unpack(gearman_packet_st " *packet ", gearman_con_st " *con ", const void " *data ", size_t " data_size ", gearman_return_t *ret_ptr);"
.SH DESCRIPTION
Unpack packet from input data.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
