.TH gearman_server_proc_packet_remove 3 2009-07-02 "Gearman" "Gearman"
.SH NAME
gearman_server_proc_packet_remove \- Server Connection Handling
.SH SYNOPSIS
.B #include <libgearman/gearman.h>
.sp
.BI "GEARMAN_APIgearman_server_packet_st *gearman_server_proc_packet_remove(gearman_server_con_st *con);"
.SH DESCRIPTION
Remove the first server packet structure from proc queue for a connection.
.SH "SEE ALSO"
The Gearman homepage: http://www.gearman.org/
.SH BUGS
Bugs should be reported at https://bugs.launchpad.net/gearmand
.SH COPYING
Copyright (C) 2008 Brian Aker, Eric Day. All rights reserved.

Use and distribution licensed under the BSD license. See the COPYING file in the original source for full text.
